apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-logging-service
  namespace: retail-banking
  labels:
    app: retail-logging-service
    environment: prod-eu
spec:
  replicas: 5
  selector:
    matchLabels:
      app: retail-logging-service
  template:
    metadata:
      labels:
        app: retail-logging-service
        environment: prod-eu
    spec:
      containers:
      - name: retail-logging-service
        image: docker.io/akshitmadanharness/retail-logging-service:latest
        ports:
        - containerPort: 8094
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: SERVICE_NAME
          value: "retail-logging-service"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8094
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8094
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: retail-logging-service
  namespace: retail-banking
  labels:
    app: retail-logging-service
    environment: prod-eu
spec:
  selector:
    app: retail-logging-service
  ports:
  - port: 8094
    targetPort: 8094
    protocol: TCP
    name: http
