apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-banking-api
  namespace: retail-banking
  labels:
    app: retail-banking-api
    environment: prod-eu
spec:
  replicas: 5
  selector:
    matchLabels:
      app: retail-banking-api
  template:
    metadata:
      labels:
        app: retail-banking-api
        environment: prod-eu
    spec:
      containers:
      - name: retail-banking-api
        image: docker.io/akshitmadanharness/retail-banking-api:latest
        ports:
        - containerPort: 8090
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: SERVICE_NAME
          value: "retail-banking-api"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: retail-banking-api
  namespace: retail-banking
  labels:
    app: retail-banking-api
    environment: prod-eu
spec:
  selector:
    app: retail-banking-api
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
    name: http
