---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: transaction-service
  namespace: retail-banking
  labels:
    app: transaction-service
    environment: prod-eu
    strategy: canary
spec:
  replicas: 5
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
        environment: prod-eu
    spec:
      containers:
      - name: transaction-service
        image: docker.io/akshitmadanharness/transaction-service:latest
        ports:
        - containerPort: 8092
        env:
        - name: ENVIRONMENT
          value: "prod-eu"
        - name: ACCOUNT_SERVICE_URL
          value: "http://account-service:8091"
        - name: FRAUD_DETECTION_URL
          value: "http://fraud-detection:8093"
        - name: DATABASE_URL
          value: "postgresql://retail-db:5432/retail_banking"
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: KAFKA_TOPIC
          value: "transactions"
        resources:
          requests:
            memory: "512Mi"
            cpu: "400m"
          limits:
            memory: "1Gi"
            cpu: "800m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8092
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8092
          initialDelaySeconds: 5
          periodSeconds: 5
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      maxSurge: '25%'
      maxUnavailable: 0
      steps:
        - setWeight: 10
        - pause:
            duration: 10m
        - setWeight: 25
        - pause:
            duration: 10m
        - setWeight: 50
        - pause:
            duration: 10m
        - setWeight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: retail-banking
  labels:
    app: transaction-service
    environment: prod-eu
spec:
  selector:
    app: transaction-service
  ports:
  - name: http
    port: 80
    targetPort: 8092
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-config
  namespace: retail-banking
  labels:
    app: transaction-service
    environment: prod-eu
data:
  ENVIRONMENT: "prod-eu"
  LOG_LEVEL: "INFO"
  ACCOUNT_SERVICE_URL: "http://account-service:8091"
  FRAUD_DETECTION_URL: "http://fraud-detection:8093"
  DATABASE_HOST: "retail-db"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "retail_banking"
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_TOPIC: "transactions"
  TRANSACTION_BATCH_SIZE: "100"
  FRAUD_CHECK_ENABLED: "true"
