---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: retail-banking-ui
  namespace: retail-banking
  labels:
    app: retail-banking-ui
    environment: prod-apac
    strategy: blueGreen
spec:
  replicas: 5
  selector:
    matchLabels:
      app: retail-banking-ui
  template:
    metadata:
      labels:
        app: retail-banking-ui
        environment: prod-apac
    spec:
      containers:
      - name: retail-banking-ui
        image: docker.io/akshitmadanharness/retail-banking-ui:latest
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "prod-apac"
        - name: REACT_APP_API_URL
          value: "https://retail-banking-api.prod-apac.svc.cluster.local"
        - name: REACT_APP_ACCOUNT_SERVICE
          value: "https://account-service.prod-apac.svc.cluster.local"
        - name: REACT_APP_TRANSACTION_SERVICE
          value: "https://transaction-service.prod-apac.svc.cluster.local"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    blueGreen:
      activeService: retail-banking-ui-active
      previewService: retail-banking-ui-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: retail-banking-ui-active
  namespace: retail-banking
  labels:
    app: retail-banking-ui
    environment: prod-apac
spec:
  selector:
    app: retail-banking-ui
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: retail-banking-ui-preview
  namespace: retail-banking
  labels:
    app: retail-banking-ui
    environment: prod-apac
spec:
  selector:
    app: retail-banking-ui
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: retail-banking-ui-config
  namespace: retail-banking
  labels:
    app: retail-banking-ui
    environment: prod-apac
data:
  ENVIRONMENT: "prod-apac"
  REACT_APP_API_URL: "https://retail-banking-api.prod-apac.svc.cluster.local"
  REACT_APP_ACCOUNT_SERVICE: "https://account-service.prod-apac.svc.cluster.local"
  REACT_APP_TRANSACTION_SERVICE: "https://transaction-service.prod-apac.svc.cluster.local"
  REACT_APP_ENV: "production"
  REACT_APP_VERSION: "latest"
  REACT_APP_FEATURE_FLAGS: "fraud_detection,real_time_alerts,advanced_analytics"
