apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: loans-api
  labels:
    app: loans-api
    strategy: canary
spec:
  replicas: 5
  selector:
    matchLabels:
      app: loans-api
  template:
    metadata:
      labels:
        app: loans-api
    spec:
      containers:
      - name: loans-api
        image: docker.io/akshitmadanharness/loans-api:v2
        ports:
        - containerPort: 8083
        env:
        - name: ENVIRONMENT
          value: "prod-na"
        resources:
          requests:
            memory: "512Mi"
            cpu: "400m"
          limits:
            memory: "1Gi"
            cpu: "800m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      maxSurge: '25%'
      maxUnavailable: 0
      steps:
        - setWeight: 10
        - pause: { duration: 10m }
        - setWeight: 25
        - pause: { duration: 10m }
        - setWeight: 50
        - pause: { duration: 10m }
        - setWeight: 100
