---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: credit-scoring
  namespace: loans
  labels:
    app: credit-scoring
    environment: prod-apac
    strategy: canary
spec:
  replicas: 5
  selector:
    matchLabels:
      app: credit-scoring
  template:
    metadata:
      labels:
        app: credit-scoring
        environment: prod-apac
    spec:
      containers:
      - name: credit-scoring
        image: docker.io/akshitmadanharness/credit-scoring:latest
        ports:
        - containerPort: 8085
        env:
        - name: ENVIRONMENT
          value: "prod-apac"
        - name: MODEL_PATH
          value: "/app/models/credit_model.pkl"
        - name: REDIS_URL
          value: "redis://credit-scoring-redis:6379"
        resources:
          requests:
            memory: "1Gi"
            cpu: "800m"
          limits:
            memory: "2Gi"
            cpu: "1600m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8085
          initialDelaySeconds: 5
          periodSeconds: 5
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      maxSurge: '25%'
      maxUnavailable: 0
      steps:
        - setWeight: 10
        - pause:
            duration: 10m
        - setWeight: 25
        - pause:
            duration: 10m
        - setWeight: 50
        - pause:
            duration: 10m
        - setWeight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: credit-scoring
  namespace: loans
  labels:
    app: credit-scoring
    environment: prod-apac
spec:
  selector:
    app: credit-scoring
  ports:
  - name: http
    port: 80
    targetPort: 8085
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: credit-scoring-config
  namespace: loans
  labels:
    app: credit-scoring
    environment: prod-apac
data:
  ENVIRONMENT: "prod-apac"
  LOG_LEVEL: "INFO"
  MODEL_PATH: "/app/models/credit_model.pkl"
  REDIS_HOST: "credit-scoring-redis"
  REDIS_PORT: "6379"
  MODEL_VERSION: "v2.1"
  SCORING_THRESHOLD: "650"
  BATCH_SIZE: "100"
