apiVersion: apps/v1
kind: Deployment
metadata:
  name: corp-banking-api
  namespace: corporate-banking
  labels:
    app: corp-banking-api
    environment: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: corp-banking-api
  template:
    metadata:
      labels:
        app: corp-banking-api
        environment: qa
    spec:
      containers:
      - name: corp-banking-api
        image: docker.io/akshitmadanharness/corp-banking-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: TREASURY_SERVICE_URL
          value: "http://treasury-service:8081"
        - name: COMPLIANCE_SERVICE_URL
          value: "http://compliance-service:8082"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: corp-banking-api
  namespace: corporate-banking
  labels:
    app: corp-banking-api
    environment: qa
spec:
  selector:
    app: corp-banking-api
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
