---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fraud-detection
  namespace: retail-banking
  labels:
    app: fraud-detection
    environment: prod-na
    strategy: canary
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
        environment: prod-na
    spec:
      containers:
      - name: fraud-detection
        image: docker.io/akshitmadanharness/fraud-detection:latest
        ports:
        - containerPort: 8093
        env:
        - name: ENVIRONMENT
          value: "prod-na"
        - name: MODEL_PATH
          value: "/app/models/fraud_model.pkl"
        - name: REDIS_URL
          value: "redis://fraud-detection-redis:6379"
        - name: ALERT_WEBHOOK_URL
          value: "https://alerts.prod-na.company.com/webhook"
        resources:
          requests:
            memory: "1Gi"
            cpu: "800m"
          limits:
            memory: "2Gi"
            cpu: "1600m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8093
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8093
          initialDelaySeconds: 5
          periodSeconds: 5
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      maxSurge: '25%'
      maxUnavailable: 0
      steps:
        - setWeight: 10
        - pause:
            duration: 10m
        - setWeight: 25
        - pause:
            duration: 10m
        - setWeight: 50
        - pause:
            duration: 10m
        - setWeight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection
  namespace: retail-banking
  labels:
    app: fraud-detection
    environment: prod-na
spec:
  selector:
    app: fraud-detection
  ports:
  - name: http
    port: 80
    targetPort: 8093
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-detection-config
  namespace: retail-banking
  labels:
    app: fraud-detection
    environment: prod-na
data:
  ENVIRONMENT: "prod-na"
  LOG_LEVEL: "INFO"
  MODEL_PATH: "/app/models/fraud_model.pkl"
  REDIS_HOST: "fraud-detection-redis"
  REDIS_PORT: "6379"
  MODEL_VERSION: "v3.2"
  FRAUD_THRESHOLD: "0.75"
  ALERT_WEBHOOK_URL: "https://alerts.prod-na.company.com/webhook"
  MODEL_RETRAIN_INTERVAL: "86400"
  BATCH_SIZE: "50"
