apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-banking-ui
  namespace: retail-banking
  labels:
    app: retail-banking-ui
    environment: preprod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: retail-banking-ui
  template:
    metadata:
      labels:
        app: retail-banking-ui
        environment: preprod
    spec:
      containers:
      - name: retail-banking-ui
        image: docker.io/akshitmadanharness/retail-banking-ui:latest
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "dev"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: retail-banking-ui
  namespace: retail-banking
  labels:
    app: retail-banking-ui
    environment: preprod
spec:
  selector:
    app: retail-banking-ui
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: LoadBalancer
