apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: latency-threshold
spec:
  metrics:
  - name: latency-p95
    interval: 5m
    successCondition: result[0] < 500
    failureLimit: 1
    provider:
      prometheus:
        address: http://prometheus.monitoring.svc.cluster.local:9090
        query: |
          histogram_quantile(
            0.95,
            sum(
              rate(http_request_duration_seconds_bucket[5m])
            ) by (le)
          )
