apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: retail-banking
  labels:
    app: account-service
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
        environment: dev
    spec:
      containers:
      - name: account-service
        image: docker.io/akshitmadanharness/account-service:latest
        ports:
        - containerPort: 8091
        env:
        - name: ENVIRONMENT
          value: "dev"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8091
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8091
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: retail-banking
  labels:
    app: account-service
    environment: dev
spec:
  selector:
    app: account-service
  ports:
  - port: 8091
    targetPort: 8091
    protocol: TCP
    name: http
