apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection
  namespace: retail-banking
  labels:
    app: fraud-detection
    environment: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
        environment: qa
    spec:
      containers:
      - name: fraud-detection
        image: docker.io/akshitmadanharness/fraud-detection:latest
        ports:
        - containerPort: 8093
        env:
        - name: ENVIRONMENT
          value: "dev"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8093
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8093
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection
  namespace: retail-banking
  labels:
    app: fraud-detection
    environment: qa
spec:
  selector:
    app: fraud-detection
  ports:
  - port: 8093
    targetPort: 8093
    protocol: TCP
    name: http
