apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: harness-gitops-admin
subjects:
- kind: ServiceAccount
  name: harness-gitops-sa
  namespace: ns-sa-harness-gitops
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
