apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: retail-banking
  labels:
    app: transaction-service
    environment: prod-apac
spec:
  replicas: 5
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
        environment: prod-apac
    spec:
      containers:
      - name: transaction-service
        image: docker.io/akshitmadanharness/transaction-service:latest
        ports:
        - containerPort: 8092
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: ACCOUNT_SERVICE_URL
          value: "http://account-service:8091"
        - name: FRAUD_DETECTION_URL
          value: "http://fraud-detection:8093"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8092
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8092
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: retail-banking
  labels:
    app: transaction-service
    environment: prod-apac
spec:
  selector:
    app: transaction-service
  ports:
  - port: 8092
    targetPort: 8092
    protocol: TCP
    name: http
