---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: corp-banking-api
  namespace: corporate-banking
  labels:
    app: corp-banking-api
    environment: prod-eu
    strategy: blueGreen
spec:
  replicas: 5
  selector:
    matchLabels:
      app: corp-banking-api
  template:
    metadata:
      labels:
        app: corp-banking-api
        environment: prod-eu
    spec:
      containers:
      - name: corp-banking-api
        image: docker.io/akshitmadanharness/corp-banking-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "prod-eu"
        - name: DATABASE_URL
          value: "postgresql://corporate-db:5432/corporate_banking"
        resources:
          requests:
            memory: "512Mi"
            cpu: "400m"
          limits:
            memory: "1Gi"
            cpu: "800m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    blueGreen:
      activeService: corp-banking-api-active
      previewService: corp-banking-api-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
---

apiVersion: v1
kind: Service
metadata:
  name: corp-banking-api-active
  namespace: corporate-banking
  labels:
    app: corp-banking-api
    environment: prod-eu
spec:
  selector:
    app: corp-banking-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: corp-banking-api-preview
  namespace: corporate-banking
  labels:
    app: corp-banking-api
    environment: prod-eu
spec:
  selector:
    app: corp-banking-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: corp-banking-api-config
  namespace: corporate-banking
  labels:
    app: corp-banking-api
    environment: prod-eu
data:
  ENVIRONMENT: "prod-eu"
  LOG_LEVEL: "INFO"
  DATABASE_HOST: "corporate-db"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "corporate_banking"
  API_RATE_LIMIT: "1000"
  CACHE_TTL: "3600"
