## Harness GitOps Agent - Overrides File
## For default overrides, please refer to https://github.com/harness/gitops-helm/blob/main/values.yaml
## Argo CD overrides can be found at https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml



# <---Harness configuration overrides--->
harness:
  identity:
    accountIdentifier: 1bvyLackQK-Hapk25-Ry4w
    orgIdentifier: default
    projectIdentifier: akshitprojectqa
    agentIdentifier: prodnagitopsdemo

  secrets:
    agentSecret: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFdWdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLUXdnZ1NnQWdFQUFvSUJBUUMxMk1pMDlQWkVSNDNECnUvanlzYmw2OUQ5SldqQU9hdVFnald1cWg1bmRMSnBVWmtKZi85dnBPUENoMGZrQTBqYlJYSStNbk5ncURiaTkKVkZTU24wUTNrQ1pEU1E5enN6Nm9sTW80YVZBcndmZGkzYWxBWXJXQ2laOC8zNkNIVWU0UURFcWxtRURLN2NVaAo2b2lIN2tnQTlDMnFFSXBMKzRPSW1IY04yWW00eUhXMVNKbjloSGMydlFqcDFDNEpuQzY2L2RVSkMvTkxNSUZyCkg4MjN3allNUGFwMmdMTFRPbzNLeTUzY1hFS2hYdUNZZ1pEZ2lJRlp5QnZWSHlQNXEvT043b0dIQ1dBU0M3bjQKWG9iSzZuS3p4K0p2T2hQOTc3YVFsWktQQ2tnRExIK0JwcVBkNUJDeFY2VWRaei9XeWFLYVcrbmVjN2tTWkpSNgpKL0tiUGlRTkFnTUJBQUVDZ2Y4NjJEMW5DQmExb01pa2JtSk5XNk1hM29iNFl2Qm5qMjU2NWptaDF2dlJGRHZTCmIxU2lnMlMyaFp6ZmFyUWdDL1lyVXJrdzMyZGw1WjRmaWR3a251eTk3ZVRnanpwcnR5VzgzNFN1cU5TMXYxNnMKbk1UaHlhSHVNNkoveEwrRDhKeG9DQW56dGVzcCtnN3dtZnpGU1RNL2tGaWllRDg3RlJ1MkJNY0VtcmVkd0hMSwpQcFZ0ODF4amZycUdmbW54Wlh5VExDaTA0T290RFBnclV2QUluc2JpTjJrOEcwZno0eHpmRnpqK3lCYktkMGRsCnREck1xMEFpT2JmSGtZMXlYbk0rTUpjL3ROQzJZNis2ekJNSkoyY2RRcGQzTktwblp5OE9qNGUwdDdQbmhXWCsKWFo3RDVPM3VWRUIxV1g3OElRWTFQK2ZBZTVWdnVWUzhiWllFYWZzQ2dZRUEzWmlGNEtYaS9USjlCVlhFbDVTTAprbVRra1dtdnBYZUc0N1l1NWc5QTJWaDBXbFpZcm9WT3BDUWZvbHlHMW5vTlpEeFEzUjZrZG1sNnBOQWVvcWVIClF1TVFPYVVoYjlBWEtRT1psRjZkZU5MdEFieUVUU0NQbzlRYXB4aFlRRzdoODhvZE91YzZ6UmlycVB0bkZ1WXAKUWFsTHIxWEN0Q0l0RTU4THFBR00xczhDZ1lFQTBoUnBGOTE3NjJicG11bkZsMFFaR2NQVUg1eStZNHZ1N2hkZwozbi9XOVNPS1dhazk1T3lWQ1ZCTHg3eHlRQzV0V25BNno5YlQ2elhlZm83MnA3VGlQRm91RFZDUWZIeWxWemdXCldiRXV3Zy95S2hsNi9CRmVkT1dKdGx1V1FLRGpNeG05eEsraHA2YlBoZ251TnpselAweno0c0hNU3lDWWZxMngKRURkc1RtTUNnWUJJajYwbkJxcnhaaHJ5S0VlYnF4U1k5MWl4RlA1akhHU2JKQWp2WklkRHBHZFZQWGtFakxwWApuVXlPaWVYTlRXSWROSEwyTlJaOWY4U2RPMWtNd2ZiVXZDMlA4cmFrT211YkRvYTN3dE9sd012RENjdjR4WFRECm5LeXRrcGN6WWh1ekRMZk5sZkgzUHVEWEVKdU5NQWpLYTNsUkRMQVk5Q2YyaU5uMFJhMnNtUUtCZ0I1UHM1b3QKNnVOY1JmaUVJbTVnOVA0eXN6aWNkUndINU1HVnZmUmNuYmRoR1dVMmRpZkJ1djlOQnFJYkhxRUVFZU1xcmxHdQp2WVVDa01mUitPVFp4SXJRdURSVG00VmF0c0NPNXlxcDFnVktKN2JMVm1Ob1hpaWZ0ZThKNS9RTFFyenN5ZVRICk1wdnVCYU5oYTIyc2JHU0Z4ZXJCNjZnclc5VnJXbERzcmtQaEFvR0FPOVNrTmhTZnR3NGxacDRXZnNIYU8zaysKTHlQazNCdWsyVVloMTNsSnZUaytSSWQwWDAwK1dKbnI1WGxpZGd3VDhnOVN1QTU1Si94YXd0NnVST1h5cnpkMgpMeFIxaFFOYW5ROTVFMndTM2RZaEc5N2VOZkxvOTQ2dTlKY3IzK3N0elU5aCtjbllMYlMrNG0xQVo5NTZXNFkzClBLelBxRVpMWTlSL2ErcSt3dkE9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
    # <---CA data overrides--->
    caData:
      enabled: false
      secret: 
    redisPassword: tQBh_thtERxLTA==

  gitopsServerHost: https://qa.harness.io/prod1/gitops
  networkPolicy:
    create: false
  createClusterRoles: true

  configMap:
    logLevel: DEBUG

    # <---Agent communication protocol details--->
    http:
      agentHttpTarget: https://qa.harness.io/gitops
      tlsEnabled: false
      certPath: /tmp/ca.bundle

    reconcile:
      appsetReconcile: true

  # <---Disaster Recovery override values--->
  disasterRecovery:
    enabled: false
    identifier: 

  # <---Openshift override values--->
  openshift:
    enabled: false
  flux:
    enabled: false
  argocdHarnessPlugin:
    enabled: false

argo-cd:
  enabled: false



# <---Agent overrides--->
agent:
  harnessName: prod-na-gitops-demo
  image:
    repository: docker.io/harness/gitops-agent
    tag: v0.108.0

  replicas: 1

  fipsEnabled: false

  autoscaling:
    enabled: false

  highAvailability: false
  # <---Agent Proxy Config overrides--->
  proxy:
    enabled: false
    httpProxy: 
    httpsProxy: 

# <---Agent upgrader overrides--->
upgrader:
  enabled: true
  image: docker.io/harness/upgrader:latest