## Harness GitOps Agent - Overrides File
## For default overrides, please refer to https://github.com/harness/gitops-helm/blob/main/values.yaml
## Argo CD overrides can be found at https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml



# <---Harness configuration overrides--->
harness:
  identity:
    accountIdentifier: 1bvyLackQK-Hapk25-Ry4w
    orgIdentifier: default
    projectIdentifier: akshitprojectqa
    agentIdentifier: prodapacgitopsdemoagent

  secrets:
    agentSecret: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUUNxc2R1Q1NTMy9SVGVGCjRzK1hiQW5kS0hMQmcxRzhQSi9qVFNjbHg2MUEwc3NpRVpLMndLU2RhakxYd1lvRC9teTZvTTRzSG5qNmt0YjEKSHFGdm9DVTd4RllhYVNJNGdrdzBYVkpQRTZCdVJDclliblR0ekRQQy91c2QyaDE2TUNSQk1oN1FiaGQvd1dpSAo3c1Q5bUIrc2RCYlR2K1FmTGNROW5pY01vQ01EZjR0YjA5dTlpRCttaHdqTlg4V3FocVRObnB0QUNaRW4yemZTCldVdnVyVzdKUDJueXh6RGw0NXFCL3d0Q3ZyRG54ZkwzTjRiM0lJMTEwMTFJZ1lZb3VEU1RoRHZjR0JpZmIwancKTG56bkQ3NUY3cENCOG1yaEFETmxHTExoVEM3TFBhNmRyQWc2NG5aVnNheS9ZUFNJSFVlUVUwTWcxUU54ZWRuTwp2TzY2QW9DVEFnTUJBQUVDZ2dFQUpNTVNYZ0JwdmlFSG9MZWs4dDByVUt5dDdseGNaWmgrN09MSWJCd1JoYlVBClY3R0dNZ0xTVVM2MmpYNGF2ZHAxUzBwbnJOdlJQVklUcG8zMndjWXhUcXB0eXRsYXErWHdDSlVTcllJeUdwMW0KeHQ4ZklybklhaFloeC9lYVFwOE1wOWZtQ0FpMTJlZHJIbDkvb0lnN1JoWm9kaWxOTmFQVE1Gd1gxK0hET0xUTQpzU3BCcFNCZ0VHdkNwaVJnaHhsb3YzNFZybkI4SU1HeXdtSU4rVUhPTjhnRHIrRTRjeW1WOVdvQVlUbkJDZGlXCis2blBJdStHakRIeXR2NWN1bUQ4N1Y2SHpoYnpYd3VTZG9SaGR3dkFUa0MzbTBPdEVtb1JQR29mOWY4SEh6WnYKV0h2UmoxcDZ1YkZIeWM3YXFqWFk3WmxJZWlVdDR5bzhMcmxXbDk3RWtRS0JnUURmQTBZdUowYjJuS2t1M1FTegpxb0x5TE4xVFJrMklmMVFpT29vK3dPcERPb01XSThXcHQxKzN0Rm5HZllDU3Q2V0Z6cENFWmM0WmszcTZycVptCjRVTDFkdCtldkIwNUNzeTNBZDYwMWRET2t3SjRubnJpVXV1YWhRSVhYT3g0ak9NL1U2alpGTi8rOWh1d2NjL3kKVHk1UUMxbXJrTmVhREd6NTBqTEtaa3F5VVFLQmdRREQ4WHJLbTk1QWRFWFFRVnRXMituRG16ZVI2WCtnUmZqcQpDeThjRUZ0TVA2UzJqT2Z1SkFFQkkxaHNuNHorR2VXZ3pPWXZweG9sUHQxMDhQTkNUcDVMZ0piOVM5S0xyVnQ0CnJFa05pT3ZnLzUyZjM3VVY2REdJV2o3K0hCTTVkRDBHSHZxQk1KVkFLMDRHbng1YWp5OS9SUVRNc0NtcWt2L0cKQVdRWHp2Ykhvd0tCZ0Z1L2F4WDl6cklTalgvY0tkMEluMHFtcm45ZUF2UE8vbnYrZlhXSHhGallMNm5pR2FYUwo3U3dVcElLR2kyalE2T1g5cjNMb3R6dktjc2x1cE1MYWxjT0tua0VkdnlBQ2syb08rT0tJdkpqZjNqcGxhTVRICnZHb2JvbHFlUGlMeVEyT0FOWXpwaTZYRzltbEd5WGcwbnljTEpGN3kvZUJBa0d6T3oxcDVidTJoQW9HQkFJdm0KTmczRERBUnBBQStaR21ZQnpmM2pMT0g1SFM2Snh4Y1R0U2NNWnFNaUxiQkpHcTlrOVhLaWtkZThjeVpaeHlIdwpLY21NUFphcU0rUHl4VHhxZFlyaTNPc3MzNzdxbjR5aE5lZDhBeTQ2VTRoNmFRaWpKL3A2dE04cHJIQXhGZ0R3CnpWckFIVkFibXpJUEdkVCt0cUxmM0hWb3NkY2Y3WTZxSDVVQUtDS1JBb0dCQUlyZU9NZXFxNnlEZTlmYWZQU3YKZjZkYVFZVjd6d1B1eHh5ZmR0WXVNa0JGWi9CS0ZNQWJJeHFxVjdMazBvRTdCdHVLYVZGekgzRkRoQUpIZjBLSgpMcDl0a0hDWkhRblk0V0ZKSnpoa1lQRXBNTGIwVGFVTmtLUnZPa0szQVRpWGFMOUt1UXdvMUJESmJwZGdvMlloCm8xRm14ZVJrTFZSR0JUTnlHK1VIZnBDTgotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
    # <---CA data overrides--->
    caData:
      enabled: false
      secret: 
    redisPassword: Uzc6gH0no7fS9Q==

  gitopsServerHost: https://qa.harness.io/prod1/gitops
  networkPolicy:
    create: false
  createClusterRoles: true

  configMap:
    logLevel: DEBUG

    # <---Agent communication protocol details--->
    http:
      agentHttpTarget: https://qa.harness.io/gitops
      tlsEnabled: false
      certPath: /tmp/ca.bundle

    reconcile:
      appsetReconcile: true

  # <---Disaster Recovery override values--->
  disasterRecovery:
    enabled: false
    identifier: 

  # <---Openshift override values--->
  openshift:
    enabled: false
  flux:
    enabled: false
  argocdHarnessPlugin:
    enabled: false

argo-cd:
  enabled: false



# <---Agent overrides--->
agent:
  harnessName: prod-apac-gitops-demo-agent
  image:
    repository: docker.io/harness/gitops-agent
    tag: v0.107.2

  replicas: 1

  fipsEnabled: false

  autoscaling:
    enabled: false

  highAvailability: false
  # <---Agent Proxy Config overrides--->
  proxy:
    enabled: false
    httpProxy: 
    httpsProxy: 

# <---Agent upgrader overrides--->
upgrader:
  enabled: true
  image: docker.io/harness/upgrader:latest