apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: approval-workflow-loans
  namespace: argocd
  labels:
    app.kubernetes.io/name: loans
    app.kubernetes.io/component: approval-workflow
    argocd.argoproj.io/application-type: approval-workflow
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: banking-alerts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: banking-alerts
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: banking
  source:
    repoURL: https://github.com/harness/banking-demo.git  # Replace with actual repo
    targetRevision: HEAD
    path: clusters/prod-na/loans
  destination:
    server: https://kubernetes.default.svc
    namespace: loans
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 1
      backoff:
        duration: 60s
        factor: 1
        maxDuration: 1m
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  revisionHistoryLimit: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: approval-workflow-config
  namespace: loans
  labels:
    app: loans
    component: approval-workflow
data:
  approval-workflow.yaml: |
    # Production Approval Workflow
    approval_workflow:
      # Environment-specific approval requirements
      environments:
        dev:
          auto_approve: true
          required_approvers: 0
          timeout: "0m"
        qa:
          auto_approve: true
          required_approvers: 1
          timeout: "30m"
          approvers:
            - harness:qa-lead
            - harness:devops
        preprod:
          auto_approve: false
          required_approvers: 2
          timeout: "60m"
          approvers:
            - harness:qa-lead
            - harness:devops-lead
            - harness:product-owner
        prod-na:
          auto_approve: false
          required_approvers: 3
          timeout: "120m"
          approvers:
            - harness:ops-lead
            - harness:sre-lead
            - harness:security-lead
            - harness:product-owner
        prod-eu:
          auto_approve: false
          required_approvers: 3
          timeout: "120m"
          approvers:
            - harness:ops-lead-eu
            - harness:sre-lead-eu
            - harness:security-lead-eu
            - harness:product-owner
        prod-apac:
          auto_approve: false
          required_approvers: 3
          timeout: "120m"
          approvers:
            - harness:ops-lead-apac
            - harness:sre-lead-apac
            - harness:security-lead-apac
            - harness:product-owner
      
      # Approval gates
      gates:
        # Security scan gate
        security_scan:
          enabled: true
          tools:
            - trivy
            - sonarqube
          fail_threshold: "high"
          timeout: "15m"
        
        # Performance testing gate
        performance_test:
          enabled: true
          tests:
            - load_test
            - stress_test
          metrics:
            - response_time_p95 < "2s"
            - error_rate < "0.01"
            - throughput > "1000 req/s"
          timeout: "30m"
        
        # Compliance check gate
        compliance_check:
          enabled: true
          frameworks:
            - PCI-DSS
            - SOX
            - GDPR  # For EU
          timeout: "10m"
        
        # Business validation gate
        business_validation:
          enabled: true
          tests:
            - smoke_tests
            - integration_tests
            - user_acceptance_tests
          timeout: "45m"
      
      # Approval notifications
      notifications:
        slack:
          channels:
            - banking-deployments
            - banking-alerts
          events:
            - approval_required
            - approval_granted
            - approval_rejected
            - deployment_completed
        email:
          recipients:
            - ops-team@company.com
            - sre-team@company.com
          events:
            - approval_required
            - approval_rejected
