apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-canary-corp-banking
  namespace: argocd
  labels:
    app.kubernetes.io/name: corporate-banking
    app.kubernetes.io/component: production-canary
    argocd.argoproj.io/application-type: canary
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: banking-alerts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: banking-alerts
spec:
  project: banking
  source:
    repoURL: https://github.com/harness/banking-demo.git  # Replace with actual repo
    targetRevision: HEAD
    path: clusters/prod-na/corporate-banking
  destination:
    server: https://kubernetes.default.svc
    namespace: corporate-banking
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
  - group: argoproj.io
    kind: Rollout
    jsonPointers:
    - /spec/strategy/canary/steps
  revisionHistoryLimit: 5
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: corp-banking-api-rollout
  namespace: corporate-banking
  labels:
    app: corp-banking-api
    version: canary
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10m}
      - setWeight: 50
      - pause: {duration: 10m}
      - setWeight: 100
      canaryService: corp-banking-api-canary
      stableService: corp-banking-api
      trafficRouting:
        istio:
          virtualService:
            name: corp-banking-api-vsvc
            routes:
            - primary
  selector:
    matchLabels:
      app: corp-banking-api
      version: canary
  template:
    metadata:
      labels:
        app: corp-banking-api
        version: canary
    spec:
      containers:
      - name: corp-banking-api
        image: corp-banking-api:{{.Values.image.tag | default "latest"}}
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "prod-na"
        - name: TREASURY_SERVICE_URL
          value: "http://treasury-service:8081"
        - name: COMPLIANCE_SERVICE_URL
          value: "http://compliance-service:8082"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
