apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: progressive-delivery-loans
  namespace: argocd
  labels:
    app.kubernetes.io/name: loans
    app.kubernetes.io/component: progressive-delivery
    argocd.argoproj.io/application-type: progressive-delivery
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: banking-alerts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: banking-alerts
    argocd.argoproj.io/analysis-run-notification: 'true'
spec:
  project: banking
  source:
    repoURL: https://github.com/harness/banking-demo.git  # Replace with actual repo
    targetRevision: HEAD
    path: clusters/prod-eu/loans
  destination:
    server: https://kubernetes.default.svc
    namespace: loans
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
  - group: argoproj.io
    kind: Rollout
    jsonPointers:
    - /spec/strategy/blueGreen
  revisionHistoryLimit: 5
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: loans-api-rollout
  namespace: loans
  labels:
    app: loans-api
    version: bluegreen
spec:
  replicas: 5
  strategy:
    blueGreen:
      activeService: loans-api-active
      previewService: loans-api-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
      prePromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: loans-api-preview
      postPromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: loans-api-active
  selector:
    matchLabels:
      app: loans-api
      version: bluegreen
  template:
    metadata:
      labels:
        app: loans-api
        version: bluegreen
    spec:
      containers:
      - name: loans-api
        image: loans-api:{{.Values.image.tag | default "latest"}}
        ports:
        - containerPort: 8083
        env:
        - name: ENVIRONMENT
          value: "prod-eu"
        - name: CREDIT_SCORING_URL
          value: "http://credit-scoring:8085"
        - name: DOCUMENT_PROCESSING_URL
          value: "http://document-processing:8084"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: loans
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 5m
    count: 10
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.monitoring.svc:9090
        query: |
          sum(rate(http_requests_total{service="{{args.service-name}}",status!~"5.."}[2m])) /
          sum(rate(http_requests_total{service="{{args.service-name}}"}[2m]))
