apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollback-strategy-corporate-banking
  namespace: argocd
  labels:
    app.kubernetes.io/name: corporate-banking
    app.kubernetes.io/component: rollback
    argocd.argoproj.io/application-type: rollback
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: banking-alerts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: banking-alerts
spec:
  project: banking
  source:
    repoURL: https://github.com/harness/banking-demo.git  # Replace with actual repo
    targetRevision: HEAD
    path: clusters/preprod/corporate-banking
  destination:
    server: https://kubernetes.default.svc
    namespace: corporate-banking
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - PrunePropagationPolicy=foreground
    - Retry=true
    retry:
      limit: 2
      backoff:
        duration: 30s
        factor: 1
        maxDuration: 2m
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  revisionHistoryLimit: 10
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rollback-config
  namespace: corporate-banking
  labels:
    app: corporate-banking
    component: rollback-config
data:
  rollback.yaml: |
    # Rollback Strategy Configuration
    rollback:
      # Automatic rollback conditions
      auto_rollback:
        enabled: true
        conditions:
          # Rollback if error rate > 5% for 5 minutes
          error_rate_threshold: 0.05
          error_rate_duration: "5m"
          # Rollback if response time > 2s for 3 minutes
          response_time_threshold: "2s"
          response_time_duration: "3m"
          # Rollback if health check fails for 2 minutes
          health_check_duration: "2m"
      
      # Manual rollback approval
      manual_approval:
        enabled: true
        approvers:
          - harness:ops
          - harness:sre
        approval_timeout: "30m"
      
      # Rollback procedure
      procedure:
        # Step 1: Pause traffic to new version
        pause_traffic: true
        # Step 2: Scale down new version
        scale_down_new: true
        # Step 3: Restore previous version
        restore_previous: true
        # Step 4: Verify rollback
        verify_rollback: true
        
      # Rollback verification
      verification:
        # Health checks
        health_checks:
          - path: /health
            expected_status: 200
            timeout: "30s"
        # Metrics verification
        metrics:
          - name: error_rate
            threshold: 0.01
          - name: response_time
            threshold: "1s"
        # Business logic verification
        business_logic:
          - endpoint: /api/v1/accounts
            method: GET
            expected_response: "accounts_list"
