---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: account-service
  namespace: retail-banking
  labels:
    app: account-service
    environment: prod-eu
    strategy: canary
spec:
  replicas: 5
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
        environment: prod-eu
    spec:
      containers:
      - name: account-service
        image: docker.io/akshitmadanharness/account-service:latest
        ports:
        - containerPort: 8091
        env:
        - name: ENVIRONMENT
          value: "prod-eu"
        - name: DATABASE_URL
          value: "postgresql://retail-db:5432/retail_banking"
        - name: REDIS_URL
          value: "redis://account-redis:6379"
        resources:
          requests:
            memory: "512Mi"
            cpu: "400m"
          limits:
            memory: "1Gi"
            cpu: "800m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8091
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8091
          initialDelaySeconds: 5
          periodSeconds: 5
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      maxSurge: '25%'
      maxUnavailable: 0
      steps:
        - setWeight: 10
        - pause:
            duration: 10m
        - setWeight: 25
        - pause:
            duration: 10m
        - setWeight: 50
        - pause:
            duration: 10m
        - setWeight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: retail-banking
  labels:
    app: account-service
    environment: prod-eu
spec:
  selector:
    app: account-service
  ports:
  - name: http
    port: 80
    targetPort: 8091
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
  namespace: retail-banking
  labels:
    app: account-service
    environment: prod-eu
data:
  ENVIRONMENT: "prod-eu"
  LOG_LEVEL: "INFO"
  DATABASE_HOST: "retail-db"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "retail_banking"
  REDIS_HOST: "account-redis"
  REDIS_PORT: "6379"
  CACHE_TTL: "3600"
  ACCOUNT_LOCK_TIMEOUT: "300"
