---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: compliance-service
  namespace: corporate-banking
  labels:
    app: compliance-service
    environment: prod-apac
    strategy: canary
spec:
  replicas: 5
  selector:
    matchLabels:
      app: compliance-service
  template:
    metadata:
      labels:
        app: compliance-service
        environment: prod-apac
    spec:
      containers:
      - name: compliance-service
        image: docker.io/akshitmadanharness/compliance-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: ENVIRONMENT
          value: "prod-apac"
        resources:
          requests:
            memory: "512Mi"
            cpu: "400m"
          limits:
            memory: "1Gi"
            cpu: "800m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      maxSurge: '25%'
      maxUnavailable: 0
      steps:
        - setWeight: 10
        - pause:
            duration: 10m
        - setWeight: 25
        - pause:
            duration: 10m
        - setWeight: 50
        - pause:
            duration: 10m
        - setWeight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: compliance-service
  namespace: corporate-banking
  labels:
    app: compliance-service
    environment: prod-apac
spec:
  selector:
    app: compliance-service
  ports:
  - name: http
    port: 80
    targetPort: 8082
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: compliance-service-config
  namespace: corporate-banking
  labels:
    app: compliance-service
    environment: prod-apac
data:
  ENVIRONMENT: "prod-apac"
  LOG_LEVEL: "INFO"
  COMPLIANCE_CHECK_INTERVAL: "300"
  AUDIT_RETENTION_DAYS: "90"
