apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-service
  namespace: corporate-banking
  labels:
    app: compliance-service
    environment: prod-apac
spec:
  replicas: 5
  selector:
    matchLabels:
      app: compliance-service
  template:
    metadata:
      labels:
        app: compliance-service
        environment: prod-apac
    spec:
      containers:
      - name: compliance-service
        image: docker.io/akshitmadanharness/compliance-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: SERVICE_NAME
          value: "compliance-service"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: compliance-service
  namespace: corporate-banking
  labels:
    app: compliance-service
    environment: prod-apac
spec:
  selector:
    app: compliance-service
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
