apiVersion: apps/v1
kind: Deployment
metadata:
  name: corp-banking-ui
  namespace: corporate-banking
  labels:
    app: corp-banking-ui
    environment: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: corp-banking-ui
  template:
    metadata:
      labels:
        app: corp-banking-ui
        environment: qa
    spec:
      containers:
      - name: corp-banking-ui
        image: docker.io/akshitmadanharness/corp-banking-ui:latest
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "dev"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: corp-banking-ui
  namespace: corporate-banking
  labels:
    app: corp-banking-ui
    environment: qa
spec:
  selector:
    app: corp-banking-ui
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: LoadBalancer
