apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-scoring
  namespace: loans
  labels:
    app: credit-scoring
    environment: prod-apac
spec:
  replicas: 5
  selector:
    matchLabels:
      app: credit-scoring
  template:
    metadata:
      labels:
        app: credit-scoring
        environment: prod-apac
    spec:
      containers:
      - name: credit-scoring
        image: docker.io/akshitmadanharness/credit-scoring:latest
        ports:
        - containerPort: 8085
        env:
        - name: ENVIRONMENT
          value: "dev"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8085
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: credit-scoring
  namespace: loans
  labels:
    app: credit-scoring
    environment: prod-apac
spec:
  selector:
    app: credit-scoring
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
    name: http
