apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-apac-microservices
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error

  generators:
  - list:
      elements:
        # -------- corporate-banking --------
        - app: compliance-service
          path: clusters/prod-apac/corporate-banking/compliance-service
          namespace: corporate-banking
        - app: corp-banking-api
          path: clusters/prod-apac/corporate-banking/corp-banking-api
          namespace: corporate-banking
        - app: corp-banking-ui
          path: clusters/prod-apac/corporate-banking/corp-banking-ui
          namespace: corporate-banking
        - app: treasury-service
          path: clusters/prod-apac/corporate-banking/treasury-service
          namespace: corporate-banking

        # -------- retail-banking --------
        - app: account-service
          path: clusters/prod-apac/retail-banking/account-service
          namespace: retail-banking
        - app: fraud-detection
          path: clusters/prod-apac/retail-banking/fraud-detection
          namespace: retail-banking
        - app: logging-service
          path: clusters/prod-apac/retail-banking/logging-service
          namespace: retail-banking
        - app: retail-banking-api
          path: clusters/prod-apac/retail-banking/retail-banking-api
          namespace: retail-banking
        - app: retail-banking-ui
          path: clusters/prod-apac/retail-banking/retail-banking-ui
          namespace: retail-banking
        - app: transaction-service
          path: clusters/prod-apac/retail-banking/transaction-service
          namespace: retail-banking

        # -------- loans --------
        - app: credit-scoring
          path: clusters/prod-apac/loans/credit-scoring
          namespace: loans
        - app: document-processing
          path: clusters/prod-apac/loans/document-processing
          namespace: loans
        - app: loans-api
          path: clusters/prod-apac/loans/loans-api
          namespace: loans
        - app: loans-ui
          path: clusters/prod-apac/loans/loans-ui
          namespace: loans

  template:
    metadata:
      name: "prod-apac-{{.app}}"
      labels:
        environment: "prod-apac"
        app: "{{.app}}"
        strategy: "rollout"
      annotations:
        argocd.argoproj.io/sync-options: "CreateNamespace=true"
        argocd.argoproj.io/compare-options: "IgnoreExtraneous"
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "prod-banking-alerts"
    spec:
      project: banking

      source:
        repoURL: https://github.com/akmadan/gitops-product-demo
        targetRevision: main
        path: "{{.path}}"

      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{.namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

      # Progressive delivery configuration for production
      ignoreDifferences:
      - group: argoproj.io
        kind: Rollout
        jsonPointers:
        - /spec/replicas
