---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: treasury-service
  namespace: corporate-banking
  labels:
    app: treasury-service
    environment: prod-eu
    strategy: canary
spec:
  replicas: 5
  selector:
    matchLabels:
      app: treasury-service
  template:
    metadata:
      labels:
        app: treasury-service
        environment: prod-eu
    spec:
      containers:
      - name: treasury-service
        image: docker.io/akshitmadanharness/treasury-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: ENVIRONMENT
          value: "prod-eu"
        - name: REDIS_URL
          value: "redis://treasury-redis:6379"
        resources:
          requests:
            memory: "512Mi"
            cpu: "400m"
          limits:
            memory: "1Gi"
            cpu: "800m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      maxSurge: '25%'
      maxUnavailable: 0
      steps:
        - setWeight: 10
        - pause:
            duration: 10m
        - setWeight: 25
        - pause:
            duration: 10m
        - setWeight: 50
        - pause:
            duration: 10m
        - setWeight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: treasury-service
  namespace: corporate-banking
  labels:
    app: treasury-service
    environment: prod-eu
spec:
  selector:
    app: treasury-service
  ports:
  - name: http
    port: 80
    targetPort: 8081
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: treasury-service-config
  namespace: corporate-banking
  labels:
    app: treasury-service
    environment: prod-eu
data:
  ENVIRONMENT: "prod-eu"
  LOG_LEVEL: "INFO"
  REDIS_HOST: "treasury-redis"
  REDIS_PORT: "6379"
  CACHE_TTL: "1800"
  RATE_LIMIT: "500"
